### ISSUE TITLE
Warn on `cond` & `condp` without default case

### ISSUE THREAD

**Issue by neotyk** [clj-kondo/clj-kondo#1164]
**Is your feature request related to a problem? Please describe.**
It's perfectly valid to have `cond` or `condp` without default case, though exception is thrown when no matching case is found.

**Describe the solution you'd like**
Warn on `cond` & `condp` used without default case.

Assuming this is really wanted I have some OSS time this Friday, just sayin'

**Comment by borkdude** [comment]
> cond doesn't throw an exception without a default case

It doesn't? 

``` 
user=> (cond (odd? 1) :true)
:true
user=> (cond (odd? 2) :true)
```

For `case` we don't lint this as a warning since case without a default case is meant to throw
I did consider this once, but this was met with feedback from e.g. Alex Miller (@puredanger) that `case` (and I think the same goes for `condp`) is meant to cover a limited set of cases and should throw when a case is unhandled. 

https://twitter.com/puredanger/status/1116696133315760128

<img width="603" alt="Screenshot 2021-02-10 at 12 41 38" src="https://user-images.githubusercontent.com/284934/107505702-6399e680-6b9d-11eb-8b76-30552fc5a5ab.png">

So as it stands, I don't think any changes are needed here.

**Comment by neotyk** [comment]
Maybe I was too trigger happy about `cond`, but `condp` is throwing:
```
(condp = 0 1 :something)
;=> Execution error (IllegalArgumentException) at dev/eval60650 (form-init4047019337742748236.clj:1).
No matching clause: 0
```

**Comment by neotyk** [comment]
Yeah oh, throwing by design. I'd still like the working for it.

**Comment by borkdude** [comment]
@neotyk Currently you can write a custom hook to check for `condp` without defaults:

``` clojure
$ clj-kondo --lint src
src/program.clj:3:1: warning: condp without default
linting took 14ms, errors: 0, warnings: 1

$ cat src/program.clj
(ns program)

(condp = 1
  2 :foo)

$ cat .clj-kondo/config.edn
{:hooks {:analyze-call {clojure.core/condp hooks/condp-hook}}
 :linters {:condp-without-default {:level :warning}}}
borkdude@MBP2019 /tmp/condp-hook $ cat .clj-kondo/hooks.clj
(ns hooks
  (:require [clj-kondo.hooks-api :as api]))

(defn condp-hook [{:keys [:node]}]
  (let [children (rest (:children node))]
    (when (even? (count children))
      (api/reg-finding! (assoc (meta node)
                               :message "condp without default"
                               :type :condp-without-default)))))
```

<img width="216" alt="Screenshot 2021-02-10 at 13 37 09" src="https://user-images.githubusercontent.com/284934/107511092-4cf78d80-6ba5-11eb-939e-c05a74572dbe.png">

**Comment by serioga** [comment]
For me the `cond` without default case is fine and handy.
