### ISSUE TITLE
Support for maps in hooks

### ISSUE THREAD

**Issue by lumimies** [clj-kondo/clj-kondo#1270]
When writing hooks, I noticed maps weren't supported, which I believe has to do with missing support for namespaced maps in rewrite-clj. I noticed #1039 was started to deal with this.

I think rewrite-clj has support for namespaced maps now, and probably exposing their constructor, 
and adding a resolver to `sexpr`, should be possible.

I'm willing to try to hack on this, if that helps, assuming the bundled version of rewrite-clj is up to date.

**Comment by borkdude** [comment]
@lumimies Hey, thanks for creating the issue! Could you explain in more detail why your hook code needs to create maps? Usually I can get away with just creating `nil` for example, while still getting the linting I need. Could you provide a real world example where this isn't the case?

**Comment by lumimies** [comment]
I was writing a hook for [plumbing](https://github.com/plumatic/plumbing)'s `fnk` family of macros, and I wanted to translate the recursive bindings into Clojure style deconstruction, which required at least a `map-node?` predicate to parse, but also a `map-node` to create the bindings, although I can probably just collect all the names and use them in a flat let

**Comment by borkdude** [comment]
@lumimies you could also create something like `(let [[x y z] ...)` instead of `(let [{:keys [x y z]}])`. 
To check if something is a map, you could also look at the `:tag` of the sexpr, this should return `:map`. Alternatively you could call `sexpr` on the node and then use clojure's `map?`. But I agree that having a predicate for this is nicer.

The problem with rewrite-clj is that is has separate node types for `{:a 1}` and `#:foo{:a 1}`. It probably makes sense to add `map-node?` and `namespaced-map-node`? since the structure of the node is differently organized. What do you think @lread?

**Comment by lumimies** [comment]
I didn't write `(let [[x y z] thing] ...)` because I was hoping this way the type checking would help me out more, in case `thing` isn't a map 😄 I did hack it up with `:tag` for now, but that required figuring out rewrite-clj's internals
