### ISSUE TITLE
Syncing clj-kondo cache with project dependencies

### ISSUE THREAD

**Issue by alexhall** [clj-kondo/clj-kondo#1286]
I'm looking at setting up clj-kondo on an existing project that uses Leiningen, with a small team of developers working on it. I'm concerned about all developers on the team having to manually rebuild their local clj-kondo caches every time project dependencies are changed. Is there a setup that would allow changes to project dependencies to be automatically synced to the cache?

**Comment by borkdude** [comment]
@alexhall Currently clj-kondo doesn't do this automatically. When a dependency changes, you can run:

```
clj-kondo --lint $(lein classpath) --dependencies --parallel
```

This will skip already linted jar files, so it should be relatively fast (although running `$(lein classpath)` isn't particularly fast in itself).

Tools like clojure-lsp will do this automatically, so if your team members adopt this in their editor workflow, then they don't have to configure anything, since clojure-lsp uses clj-kondo for linting.

**Comment by alexhall** [comment]
Thanks @borkdude -- that's more or less what I expected but wanted to confirm. We've got some old-timers on the project still using emacs with CIDER and https://github.com/borkdude/flycheck-clj-kondo but maybe this will be enough to nudge us towards clojure-lsp.

It also seems like it should be possible to write a lein plugin to hook the dependency tooling and invoke clj-kondo when new dependencies are downloaded - I might have a go at that as an evening project if time allows.

**Comment by borkdude** [comment]
There is now lein-clj-kondo. https://github.com/clj-kondo/lein-clj-kondo
