### ISSUE TITLE
[Analysis] Support from-var on var usages that occur in the body of a re-frame macro

### ISSUE THREAD

**Issue by benedekfazekas** [clj-kondo/clj-kondo#1461]
**Is your feature request related to a problem? Please describe.**

Although re-frame macros are like vars (functions) they named with keywords instead symbols. Clj-kondo analysis already considers them as such and uses the `:reg` keyword to mark where these special vars are defined.
However, the body of these macros (functions) are not processed the same way as a var/function body, specifically other vars in the body don't register the reg name in a `from-var` attribute

**Describe the solution you'd like**
I'd like the `from-var` attribute of the vars used in the body of a re-frame macro filled with the name of the re-frame macro

**Additional context**
This would help for tools to make connections between re-frame macros and other ordinary clojure vars in usage graphs and the like.

PR is coming up for this.

**Comment by borkdude** [comment]
First of all, thanks for splitting this up in more bite-sized portions so it's easier for me to reason about individual components.

1. Why is it important to know from which registered event a var was called? Can you give a practical example?

2. I don't think the name `from-var` describes well what is happening here, although I appreciate the attempt to make the name more general than a re-frame specific concept.

3. Issue. In the output `::a` is translated to `{:name constantly :from-var "a" :reg re-frame.core/reg-event-db}` where the namespace is lost. You probably added `:from-ns` for this reason.

4. Proposal which addresses both 2 and 3 and for which we already have an issue:

As an alternative to adding bespoke keys to the analysis output for re-frame, I think it's better to introduce a more general `:context` attribute where both clj-kondo and custom hooks can add ... context, so the output will look like:

```
{:name constantly :context {:re-frame.core/reg-event-db :user/a}}
```

/cc @ericdallo

**Comment by borkdude** [comment]
I think I'll have something to show tomorrow.

**Comment by ericdallo** [comment]
So context could be anything right? I think it's ok but I'd avoid adding to much on that field as things would become more generic, I don't know

**Comment by borkdude** [comment]
@ericdallo Yes, it is supposed to be a solution both for built-in functionality but also for custom hooks, so we should allow anything. Any data added there will end up in the analysis and tools like morpheus can do whatever they want with it.

**Comment by borkdude** [comment]
Dump from a Slack conversation with Benedek: 

borkdude:clj-kondo: So my plan is to support a :context element that hooks (or built-ins) can add to any rewrite-clj node. In the case of the built-in re-frame function:

``` clojure
(defn analyze-reg [ctx expr fq-def]
  (let [[name-expr & body] (next (:children expr))
        [ctx reg-val] (if-let [kw (:k name-expr)]
                        [(assoc-in ctx [:context fq-def] (meta name-expr))
                         (-> name-expr
                             (assoc :reg fq-def)
                             (assoc-in [:context fq-def] true))]
                        [ctx  name-expr])]
    (common/analyze-children ctx (cons reg-val body))))
```

So what happens here: to the name node, a context with fq-def true gets added. Also we add to the clj-kondo ctx itself a context with fq-def + meta of the name-expr (which contains row and col). This will attach the context to all the nodes that are analyzed with this ctx.
When executing this, you will now see:

````
(-> (with-in-str "(require '[re-frame.core :as re-frame]) (re-frame/reg-sub ::foo (fn [x] (inc x)))"
        (clj-kondo/run! {:lang :cljs :lint ["-"] :config {:output {:analysis {:keywords true}}}}))
      :analysis :var-usages)
{:fixed-arities #{1},
  :end-row 1,
  :name-end-col 77,
  :name-end-row 1,
  :name-row 1,
  :name inc,
  :filename "<stdin>",
  :from user,
  :col 73,
  :name-col 74,
  :context #:re-frame.core{reg-sub {:row 1, :col 59, :end-row 1, :end-col 64}},
  :end-col 80,
  :arity 1,
  :row 1,
  :to cljs.core}
 {:end-row 1,
  :name-end-col 68,
  :name-end-row 1,
  :name-row 1,
  :name fn,
  :filename "<stdin>",
  :from user,
  :macro true,
  :col 65,
  :name-col 66,
  :context #:re-frame.core{reg-sub {:row 1, :col 59, :end-row 1, :end-col 64}},
  :end-col 81,
  :arity 2,
  :varargs-min-arity 0,
  :row 1,
  :to cljs.core}
 ```

10:58 AM
So in var-usages, vars that are used within the re-frame reg-sub, get:
:context #:re-frame.core{reg-sub {:row 1, :col 59, :end-row 1, :end-col 64}}
10:58 AM
This is just an example, the exact key/vals can change, but this is the idea
11:01 AM
So instead of mapping re-frame concepts on existing keys like "from" we can have more accurate information which can be used for multiple purposes. E.g. finding unused subscriptions, etc.
11:03 AM
benedek hm quite a bit of food for thougth here… the nice thing by reusing from-var from my (morpheus) point of view was that this is essentially the same semantics as any var/function. so re-frame things are just handled almost as vars/functions. that said i need to recheck my facts here (review my changes in the corresponding branch of morpheus)
11:03 AM
but essentially let me think about this a bit
11:04 AM
borkdude:clj-kondo: from-var isn't an existing key in the analysis, it was called from ;)
11:04 AM
benedek i will also answer your question on the PR and that may be relevant to this context too
11:04 AM
oh, did i introduce it?
11:05 AM
borkdude:clj-kondo: oh no I'm wrong
11:05 AM
it was from + from-var
11:05 AM
the first from should have been from-ns maybe, but bad naming can't be undone
11:05 AM
benedek uh.. you almost got me there :wink:
11:05 AM
borkdude:clj-kondo: sorry :)
11:06 AM
so what happens when you write:
(defn foo [] (reg-sub ....))
It's uncommon, but can happen. Mapping re-frame (and clojure.spec) keys on vars is maybe convenient for your use case, but I think it's good to keep things more separate.
11:07 AM
We can e.g. support :context {:re-frame <subscription-name>}
11:07 AM
or whatever
11:10 AM
benedek fair point, maybe keeping these things separate would make sense
11:10 AM
borkdude:clj-kondo: If we were staying within the :reg paradigm, then it would be :from-reg or so, but I think :reg is a bad design: it only allows you to add one thing. :context is just a map to which you can add things as you like.
11:11 AM
so we could add :from-re-frame-reg ... (edited) 
11:11 AM
benedek so we have two questions/topics/issues here:
introduction of context
if re-frame things should be handled semantically separate from vars/functions
11:11 AM
the danger of such a :context approach is a fuzzy, not very well defined interface I guess
11:12 AM
how can tools expect certain things in the context under certain names when anything can be there — this may not be a problem ofc
11:12 AM
borkdude:clj-kondo: the interface is defined by:
built-in things, we can document those.
custom hooks: custom hooks should document what they add there
11:12 AM
benedek fair points

**Comment by benedekfazekas** [comment]
after sleeping on it i am happy to go with the context idea, but unsure how to proceed.

so shall I give the context thing a try by reworking the existing two new PRs? that would give me enough to test how the client would like in a new morpheus branch. are you happy to have this in core (well `analyze-reg` is already in core) or should I rather look into doing something minimal that can be then used by custom hooks and implement the extra analysis for re-frame specifics in hooks?

just to make clear my position on this I think re-frame is widespread and popular enough to have core support but happy to go the hook way too

**Comment by borkdude** [comment]
@benedekfazekas I'll push my context work to a branch, so you can see what I did and you can make some tweaks to that that might better fit your needs: renaming etc. 

I think supporting re-frame out of the box is good, but let's try to do it in such a way that can be done in a similar way by custom hooks.

**Comment by benedekfazekas** [comment]
sounds good. let me know when you have that branch ready

**Comment by borkdude** [comment]
Pushed it to the `context` branch.
