### ISSUE TITLE
analyse: symbols in `:or` mapping of map destructuring forms

### ISSUE THREAD

**Issue by DeLaGuardo** [clj-kondo/clj-kondo#2068]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
The problem originated in clojure-lsp/clojure-lsp#1562
TLDR; there is no analysis for symbols in `:or` part of destructuring forms which is needed by clojure-lsp to apply rename action

**Comment by borkdude** [comment]
@ericdallo 

If we include the :or default in `:local-usages` we might get false positive unused bindings if they aren't really used beyond this. E.g. `(let [{:keys [a] :or {a 1}} {}] nil)`.

But we if include it in `:locals` this would be weird too, since there can be only one definition of a local.

**Comment by ericdallo** [comment]
Sounds good enough ignore linting, don't see any problems with that
