### ISSUE TITLE
Warn on quoted symbols as test constants in case expression

### ISSUE THREAD

**Issue by viesti** [clj-kondo/clj-kondo#593]
Recently I found myself in a conversation where nested if/else code was chosen instead of `case` expression because it was hard to understand how `case` works if a constant tucked behind a var is used as a test constant:

```clojure
user=> (def the-answer 42)
#'user/the-answer
user=> (let [result 42]
  #_=>   (case result
  #_=>     the-answer :yay
  #_=>     :lolnay))
:lolnay
```

Symbols as test constants in case expression are probably a bit rare thing to come by. Maybe it would be good to have a warning about such use.

 Initially mentioned this in [another issue](https://github.com/borkdude/clj-kondo/issues/587#issuecomment-550401802), but probably better to tackle this conversation separately :)

**Comment by borkdude** [comment]
@viesti I regularly use symbols in case expressions myself. Since this is valid behavior I don't think warning about it will be a good enhancement. Although I do sometimes make the mistake of quoting values in case, like:

```
(case x 'foo 1)
```
which won't match if `x` equals `(symbol "foo")`, so I think a warning about that would be appropriate.
