### ISSUE TITLE
Document and test unsorted-required-namespaces linter for multiple requires

### ISSUE THREAD

**Issue by serioga** [clj-kondo/clj-kondo#792]
In case of multiple `:require` declarations the `unsorted-required-namespaces` linter checks every declaration independently.

This is useful behavior which could be documented and captured inside a unit test.

**Comment by borkdude** [comment]
Feel free to also post your example from Slack here.

**Comment by borkdude** [comment]
```
(:require
    ; systems
    [app.app-system.service.app-config]
    [app.app-system.service.hikari-data-source]
    [app.app-system.service.immutant-web]
    [app.app-system.service.mount]
    [app.app-system.service.webapp-http-handler]
    [app.app-system.task.database-migration]
    ; imports
    [app.app-system.impl :as impl]
    [app.lib.util.integrant :as ig-util]
    [integrant.core :as ig])
```

**Comment by serioga** [comment]
The example from above was rewritten with multiple requires which works as expected:
```clojure
(ns app.app-system.core
  (:require ; systems
    [app.app-system.service.app-config]
    [app.app-system.service.hikari-data-source]
    [app.app-system.service.immutant-web]
    [app.app-system.service.mount]
    [app.app-system.service.webapp-http-handler]
    [app.app-system.task.database-migration])
  (:require ; imports
    [app.app-system.impl :as impl]
    [app.lib.util.integrant :as ig-util]
    [integrant.core :as ig]))
```

**Comment by didibus** [comment]
Hum... Shouldn't we just warn against using multiple `:require` clause inside the `ns` macro? That seems wrong to me.

**Comment by borkdude** [comment]
Multiple requires are not encouraged in Clojure. Instead of supporting this, we should warn against doing that in clj-kondo. Feel free to make a new issue about that.

Some references:

- In CLJS it is forbidden:  https://clojure.atlassian.net/browse/CLJS-254
- https://groups.google.com/g/clojure-dev/c/6EEfdPhrWgk (mostly opinion)
- https://clojurians-log.clojureverse.org/clojure/2020-07-27/1595872486.471000, where the linked article by Stuart Sierra says: Use each clause at most once.

Also, multiple `:require` might not play well with new features (`:as-alias`) in Clojure 1.11 if I understood @puredanger correctly the other day.
