### ISSUE TITLE
Built-in arity infomation of JavaScript functions

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#90]
Using a document like https://github.com/google/closure-compiler/blob/081e13cca07a3bce2807f94406164bc37439cf91/externs/es3.js
we might be able to extract arities of common JS functions.

**Comment by borkdude** [comment]
We might use the Google Closure compiler to get this info:

```
$ clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "1.10.520"}}}'
Clojure 1.10.1
user=> (import '[com.google.javascript.jscomp.parsing.parser Parser Parser$Config SourceFile])
com.google.javascript.jscomp.parsing.parser.SourceFile
user=> (def prog (.parseProgram (Parser. (Parser$Config.) nil (SourceFile. "foo" "var x = 10;"))))
#'user/prog
user=> (.-sourceElements prog)
[#object[com.google.javascript.jscomp.parsing.parser.trees.VariableStatementTree 0x61bcd567 "VARIABLE_STATEMENT@<foo(1, 1) - foo(1, 12)>"]]
```

**Comment by kolharsam** [comment]
Hey @borkdude, I'd like to help build this. How can I get started?

**Comment by borkdude** [comment]
@kolharsam You can check the script `script/extract-java` to see how arity information is extracted and processed for Java libraries. Currently this is done by processing javadocs, but using reflection is in hindsight a far more ergonomic way of obtaining both arity and type information.
When I wrote this issue I looked around at various sources but could not find good documents or tools that provided arity information about standard JavaScript functions. So step 1 would be something like that. Step 2 would be to generate similar files as the Java arity information. Step 3 would be writing some tests with expected inputs and outputs. Step 4 would be to fix those tests by improving the code, if that doesn't work already. You could also start with some hypothetical data for step 1.

**Comment by borkdude** [comment]
Btw, a limitation to the Java arity information is that it only works for static methods. In practice I've rarely seen clj-kondo warn about something I was doing wrong when it comes to Java methods.

**Comment by kolharsam** [comment]
Hey @borkdude, every function has a property called `length`, I think we can leverage that. And like `script/extract-java` does the arity information have to be a shell script? Instead of javadocs, I think we can use node(if it is available)? 

I also wanted to know where would the JS function arity and type information help in `clj-kondo`? 

For step 1 I think we can use the link you've put up here: https://github.com/borkdude/clj-kondo/issues/90#issue-433306427 alongside this: https://github.com/jsdoc2md/jsdoc-parse - or we could build a small JSDoc parser ourselves and get the required information.

How would you like me to proceed?

**Comment by borkdude** [comment]
@kolharsam About the `.length` property, can you explain how this example works?

```
Math.max.length
2
Math.max(1,2,3,4,6)
6
```

> I also wanted to know where would the JS function arity and type information help in clj-kondo?

When calling functions like `(Math/abs 1 2 3)` they would help checking that the arity should only be 1 instead of 3. But like I said, I've almost never had clj-kondo complain about a wrong arity of a Java class, so it's not that common and maybe not so important. That's why this ticket is marked low priority. 

> How would you like me to proceed?

I don't have a strong preference, as long as the program can extract the right data.

**Comment by kolharsam** [comment]
Alright, I'll get started with Step 1 for now.

**Comment by kolharsam** [comment]
@borkdude where do I add the JS files? I would want to set up an npm project somewhere within the project.

**Comment by borkdude** [comment]
@kolharsam Maybe in `$PROJECT_ROOT/extract/javascript`?

**Comment by kolharsam** [comment]
@borkdude I've been able to generate a decent JSON file with the information that could be obtained from the file that you've linked above. Certain docs could not be parsed correctly since closure compiler docs use additional tags along with ones present in the JSDoc spec.

You can see the progress here: https://github.com/borkdude/clj-kondo/pull/879

Is this good enough? Any suggestions?
